[package]
authors = ["The Cranelift Project Developers"]
name = "cranelift-reader"
version = "0.89.0"
description = "Cranelift textual IR reader"
license = "Apache-2.0 WITH LLVM-exception"
documentation = "https://docs.rs/cranelift-reader"
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition = "2021"

[dependencies]
cranelift-codegen = { path = "../codegen", version = "0.89.0" }
smallvec = "1.6.1"
target-lexicon = "0.12"

[badges]
maintenance = { status = "experimental" }

[features]
default = []
experimental_x64 = []
