[package]
name = "wasmtime-c-api-macros"
version = "0.19.0"
authors = ["The Wasmtime Project Developers"]
edition = "2021"
publish = false

[lib]
proc-macro = true
test = false

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"
