[package]
name = "wasmtime-runtime"
version = "2.0.0"
authors = ["The Wasmtime Project Developers"]
description = "Runtime library support for Wasmtime"
documentation = "https://docs.rs/wasmtime-runtime"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/bytecodealliance/wasmtime"
edition = "2021"

[dependencies]
wasmtime-asm-macros = { path = "../asm-macros", version = "=2.0.0" }
wasmtime-environ = { path = "../environ", version = "=2.0.0" }
wasmtime-fiber = { path = "../fiber", version = "=2.0.0", optional = true }
wasmtime-jit-debug = { path = "../jit-debug", version = "=2.0.0", features = ["gdb_jit_int"] }
libc = { version = "0.2.112", default-features = false }
log = "0.4.8"
memoffset = "0.6.0"
indexmap = "1.0.2"
thiserror = "1.0.4"
cfg-if = "1.0"
rand = "0.8.3"
anyhow = "1.0.38"
memfd = { version = "0.6.1", optional = true }
paste = "1.0.3"
encoding_rs = { version = "0.8.31", optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
mach = "0.3.2"

[target.'cfg(unix)'.dependencies]
rustix = { version = "0.35.6", features = ["mm"] }

[target.'cfg(target_os = "windows")'.dependencies.windows-sys]
version = "0.36.0"
features = [
  "Win32_System_Kernel",
  "Win32_System_Memory",
  "Win32_System_Diagnostics_Debug",
  "Win32_System_SystemInformation",
  "Win32_Storage_FileSystem",
  "Win32_Security",
]

[build-dependencies]
cc = "1.0"

[badges]
maintenance = { status = "actively-developed" }

[features]
memory-init-cow = ['memfd']

async = ["wasmtime-fiber"]

# Enables support for the pooling instance allocator
pooling-allocator = []

# Enables trap handling using POSIX signals instead of Mach exceptions on MacOS.
# It is useful for applications that do not bind their own exception ports and
# need portable signal handling.
posix-signals-on-macos = []

component-model = [
  "wasmtime-environ/component-model",
  "dep:encoding_rs",
]
