[package]
name = "wasmtime-environ"
version = "2.0.0"
authors = ["The Wasmtime Project Developers"]
description = "Standalone environment support for WebAsssembly code in Cranelift"
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/bytecodealliance/wasmtime"
documentation = "https://docs.rs/wasmtime-environ/"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
edition = "2021"

[dependencies]
anyhow = "1.0"
cranelift-entity = { path = "../../cranelift/entity", version = "0.89.0" }
wasmtime-types = { path = "../types", version = "2.0.0" }
wasmparser = { path = "../wasmparser", version = "0.89.0"}
indexmap = { version = "1.0.2", features = ["serde-1"] }
thiserror = "1.0.4"
serde = { version = "1.0.94", features = ["derive"] }
log = { version = "0.4.8", default-features = false }
gimli = { version = "0.26.0", default-features = false, features = ['read'] }
object = { version = "0.29.0", default-features = false, features = ['read_core', 'write_core', 'elf'] }
target-lexicon = "0.12"
wasm-encoder = { version = "0.16.0", optional = true }
wasmprinter = { version = "0.2.39", optional = true }
wasmtime-component-util = { path = "../component-util", version = "=2.0.0", optional = true }

[dev-dependencies]
atty = "0.2.14"
clap = { version = "3.2.8", features = ['derive'] }
env_logger = "0.9.0"
wat = "1.0.48"

[[example]]
name = "factc"
required-features = ['component-model']

[badges]
maintenance = { status = "actively-developed" }

[features]
component-model = [
  "dep:wasm-encoder",
  "dep:wasmprinter",
  "dep:wasmtime-component-util",
]
