// #![allow(non_upper_case_globals)]
// #![allow(non_camel_case_types)]
// #![allow(non_snake_case)]
// // There is a lot of code in bindings.rs which is unused
// #![allow(dead_code)]
// // include libsensors bindings generated by bindgen
// // include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
// use sensors_sys;
// use std::collections::HashMap;
// use std::ffi::CStr;
// use std::os::raw;
// use std::ptr;
// use std::str;

// const FEATURE_INIT_COUNT: i32 = 10;

// struct SensorValueWrapper {
//     name: *const sensors_chip_name,
//     subfeature_number: i32,
// }

// pub struct LmSensors {
//     subfeatures: HashMap<String, SensorValueWrapper>,
//     init_count: i32,
// }

// pub fn get_lm_sensors() -> LmSensors {
//     LmSensors {
//         subfeatures: HashMap::new(),
//         init_count: 0,
//     }
// }

// impl Drop for LmSensors {
//     fn drop(&mut self) {
//         if !self.subfeatures.is_empty() {
//             println!("executing lm_sensors cleanup");
//             unsafe {
//                 sensors_cleanup();
//             }
//         }
//     }
// }

// impl LmSensors {
//     pub fn init(&mut self) {
//         let mut subfeature_map: HashMap<String, SensorValueWrapper> = HashMap::new();

//         let relevant_keys: HashMap<&str, &str> = vec![
//             ("k10temp/temp1_input", "lm_sensors_tctl"),
//             ("k10temp/temp2_input", "lm_sensors_tdie"),
//             ("asusec/temp2_input", "lm_sensors_cpu_temp"),
//             ("asusec/temp3_input", "lm_sensors_mb_temp"),
//             ("asusec/temp1_input", "lm_sensors_chipset_temp"),
//             // NZXT kraken2 data
//             ("kraken2/temp1_input", "aio_liquid_temp"),
//             ("kraken2/fan1_input", "aio_fan_speed"),
//             ("kraken2/fan2_input", "aio_pump_speed"),
//             // amdgpu sensors
//             ("amdgpu/in0_input", "amdgpu_vddgfx_voltage"),
//             ("amdgpu/fan1_input", "amdgpu_fan1_speed"),
//             ("amdgpu/temp2_input", "amdgpu_junction_temp"),
//             ("amdgpu/temp3_input", "amdgpu_mem_temp"),
//             ("amdgpu/power1_average", "amdgpu_slowppt_wattage"),
//             // wireless adapater
//             ("iwlwifi_1/temp1_input", "wireless_temp"),
//             // logitech mouse voltage
//             ("hidpp_battery_0/in0_input", "mouse_battery_voltage"),
//         ]
//         .into_iter()
//         .collect();

//         unsafe {
//             println!("lm_sensors initialization started");
//             if self.init_count > 0 {
//                 println!("calling sensors_cleanup");
//                 sensors_cleanup();
//             }
//             println!("calling sensors_init(null)");
//             if sensors_init(ptr::null_mut()) != 0 {
//                 panic!("lm_sensors init failed");
//             }

//             let mut chip_next: raw::c_int = 0;
//             let chip_next_ptr: *mut raw::c_int = &mut chip_next;
//             loop {
//                 let chip = sensors_get_detected_chips(ptr::null_mut(), chip_next_ptr);
//                 if chip.is_null() {
//                     break;
//                 }

//                 let prefix = CStr::from_ptr((*chip).prefix).to_str().unwrap();
//                 let path = CStr::from_ptr((*chip).path).to_str().unwrap();
//                 println!("Found chip with prefix {} and path {}", prefix, path);

//                 let mut feature_next: raw::c_int = 0;
//                 let feature_next_ptr: *mut raw::c_int = &mut feature_next;

//                 loop {
//                     let feature = sensors_get_features(chip, feature_next_ptr);
//                     if feature.is_null() {
//                         break;
//                     }

//                     let feature_name = CStr::from_ptr((*feature).name).to_str().unwrap();
//                     println!("Found feature {} from chip {}", feature_name, prefix);

//                     let mut subfeature_next: raw::c_int = 0;
//                     let subfeature_next_ptr: *mut raw::c_int = &mut subfeature_next;

//                     loop {
//                         let subfeature =
//                             sensors_get_all_subfeatures(chip, feature, subfeature_next_ptr);
//                         if subfeature.is_null() {
//                             break;
//                         }
//                         let subfeature_name = CStr::from_ptr((*subfeature).name).to_str().unwrap();
//                         println!(
//                             "\t\tFound subfeature_name {} with number {}",
//                             subfeature_name,
//                             (*subfeature).number
//                         );

//                         if ((*subfeature).flags & SENSORS_MODE_R) != 0 {
//                             let key = format!("{}/{}", prefix, subfeature_name);
//                             if relevant_keys.contains_key(key.as_str()) {
//                                 println!("Found interesting key {}/{}", prefix, subfeature_name);
//                                 subfeature_map.insert(
//                                     relevant_keys.get(key.as_str()).unwrap().to_string(),
//                                     SensorValueWrapper {
//                                         name: chip,
//                                         subfeature_number: (*subfeature).number,
//                                     },
//                                 );
//                             } else {
//                                 println!("Ignoring key {}/{}", prefix, subfeature_name);
//                             }
//                         } else {
//                             println!("Ignoring non-readable sensor");
//                         }
//                     }
//                 }
//             }
//             println!("lm_sensors initialization complete");
//         }
//         self.subfeatures = subfeature_map;
//         self.init_count += 1;
//     }

//     pub fn get_lm_sensor_metrics(&mut self) -> String {
//         let mut result = String::new();
//         if self.init_count < FEATURE_INIT_COUNT {
//             self.init()
//         }
//         for (key, subfeature) in self.subfeatures.iter() {
//             let mut value = 0f64;
//             let value_ptr: *mut f64 = &mut value;
//             unsafe {
//                 if sensors_get_value(subfeature.name, subfeature.subfeature_number, value_ptr) != 0
//                 {
//                     println!("Could not get sensor value {}", key);
//                     continue;
//                 }
//             }
//             result.push_str(&format!("{} {}\n", key, value));
//         }
//         result
//     }
// }

use std::collections::BTreeMap;
use tracing::{debug_span, info, info_span};
use tracing_subscriber::Layer;
use tracing_subscriber::prelude::*;

pub struct CustomLayer;

impl<S> Layer<S> for CustomLayer
where
    S: tracing::Subscriber,
    S: for<'lookup> tracing_subscriber::registry::LookupSpan<'lookup>,
{
    fn on_new_span(
        &self,
        attrs: &tracing::span::Attributes<'_>,
        id: &tracing::span::Id,
        ctx: tracing_subscriber::layer::Context<'_, S>,
    ) {
        let span = ctx.span(id).unwrap();
        let mut fields = BTreeMap::new();
        let mut visitor = JsonVisitor(&mut fields);
        attrs.record(&mut visitor);
        let storage = CustomFieldStorage(fields);
        let mut extensions = span.extensions_mut();
        extensions.insert(storage);
    }

    fn on_event(&self, event: &tracing::Event<'_>, ctx: tracing_subscriber::layer::Context<'_, S>) {
        // All of the span context
        let scope = ctx.event_scope(event).unwrap();
        let mut spans = vec![];
        for span in scope.from_root() {
            let extensions = span.extensions();
            let storage = extensions.get::<CustomFieldStorage>().unwrap();
            let field_data: &BTreeMap<String, serde_json::Value> = &storage.0;
            spans.push(serde_json::json!({
                "target": span.metadata().target(),
                "name": span.name(),
                "level": format!("{:?}", span.metadata().level()),
                "fields": field_data,
            }));
        }

        // The fields of the event
        let mut fields = BTreeMap::new();
        let mut visitor = JsonVisitor(&mut fields);
        event.record(&mut visitor);

        // And create our output
        let output = serde_json::json!({
            "target": event.metadata().target(),
            "name": event.metadata().name(),
            "level": format!("{:?}", event.metadata().level()),
            "fields": fields,
            "spans": spans,
        });
        println!("{}", serde_json::to_string_pretty(&output).unwrap());
    }
}

struct JsonVisitor<'a>(&'a mut BTreeMap<String, serde_json::Value>);

impl<'a> tracing::field::Visit for JsonVisitor<'a> {
    fn record_f64(&mut self, field: &tracing::field::Field, value: f64) {
        self.0
            .insert(field.name().to_string(), serde_json::json!(value));
    }

    fn record_i64(&mut self, field: &tracing::field::Field, value: i64) {
        self.0
            .insert(field.name().to_string(), serde_json::json!(value));
    }

    fn record_u64(&mut self, field: &tracing::field::Field, value: u64) {
        self.0
            .insert(field.name().to_string(), serde_json::json!(value));
    }

    fn record_bool(&mut self, field: &tracing::field::Field, value: bool) {
        self.0
            .insert(field.name().to_string(), serde_json::json!(value));
    }

    fn record_str(&mut self, field: &tracing::field::Field, value: &str) {
        self.0
            .insert(field.name().to_string(), serde_json::json!(value));
    }

    fn record_error(
        &mut self,
        field: &tracing::field::Field,
        value: &(dyn std::error::Error + 'static),
    ) {
        self.0.insert(
            field.name().to_string(),
            serde_json::json!(value.to_string()),
        );
    }

    fn record_debug(&mut self, field: &tracing::field::Field, value: &dyn std::fmt::Debug) {
        self.0.insert(
            field.name().to_string(),
            serde_json::json!(format!("{:?}", value)),
        );
    }
}

#[derive(Debug)]
struct CustomFieldStorage(BTreeMap<String, serde_json::Value>);

pub fn get_trace() {
    let subscriber = tracing_subscriber::registry()
        .with(tracing_subscriber::EnvFilter::new("info"))
        .with(CustomLayer);

    tracing::subscriber::with_default(subscriber, || {
        let outer_span = info_span!("outer", level = 0);
        let _outer_entered = outer_span.enter();

        let inner_span = debug_span!("inner", level = 1);
        let _inner_entered = inner_span.enter();

        info!(a_bool = true, answer = 42, message = "first example");
    });
}
