name: 'wasmtime github releases'
description: 'wasmtime github releases'
inputs:
  token:
    description: ''
    required: true
  files:
    description: ''
    required: true
runs:
  using: 'node12'
  main: 'main.js'
