[package]
name = "wasmtime-wasi"
version = "2.0.0"
authors = ["The Wasmtime Project Developers"]
description = "WASI implementation in Rust"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition = "2021"
include = ["src/**/*", "README.md", "LICENSE", "build.rs"]
build = "build.rs"

[dependencies]
wasi-common = { path = "../wasi-common", version = "=2.0.0" }
wasi-cap-std-sync = { path = "../wasi-common/cap-std-sync", version = "=2.0.0", optional = true }
wasi-tokio = { path = "../wasi-common/tokio", version = "=2.0.0", optional = true }
wiggle = { path = "../wiggle", default-features = false, version = "=2.0.0", features = ["wasmtime_integration"] }
wasmtime = { path = "../wasmtime", default-features = false, version = "2.0.0" }
anyhow = "1.0"

[features]
default = ["sync"]
sync = ["wasi-cap-std-sync"]
tokio = ["wasi-tokio", "wasmtime/async", "wiggle/wasmtime_async"]
