[package]
name = "wasmtime-jit"
version = "2.0.0"
authors = ["The Wasmtime Project Developers"]
description = "JIT-style execution for WebAsssembly code in Cranelift"
documentation = "https://docs.rs/wasmtime-jit"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/bytecodealliance/wasmtime"
edition = "2021"

[dependencies]
wasmtime-environ = { path = "../environ", version = "=2.0.0" }
wasmtime-jit-debug = { path = "../jit-debug", version = "=2.0.0", features = ["perf_jitdump"], optional = true }
wasmtime-runtime = { path = "../runtime", version = "=2.0.0" }
thiserror = "1.0.4"
target-lexicon = { version = "0.12.0", default-features = false }
anyhow = "1.0"
cfg-if = "1.0"
gimli = { version = "0.26.0", default-features = false, features = ["std", "read"] }
object = { version = "0.29.0", default-features = false, features = ["std", "read_core", "elf"] }
serde = { version = "1.0.94", features = ["derive"] }
addr2line = { version = "0.17.0", default-features = false }
bincode = "1.2.1"
rustc-demangle = "0.1.16"
cpp_demangle = "0.3.2"
log = "0.4.8"

[target.'cfg(target_os = "windows")'.dependencies.windows-sys]
version = "0.36.0"
features = [
  "Win32_System_Diagnostics_Debug",
]

[target.'cfg(target_os = "linux")'.dependencies]
rustix = { version = "0.35.6", features = ["process"] }

[target.'cfg(target_arch = "x86_64")'.dependencies]
ittapi = { version = "0.3.0", optional = true  }

[features]
jitdump = ['wasmtime-jit-debug']
vtune = ['ittapi']

[badges]
maintenance = { status = "actively-developed" }
