[package]
name = "cranelift-filetests"
authors = ["The Cranelift Project Developers"]
version = "0.73.0"
description = "Test driver and implementations of the filetest commands"
license = "Apache-2.0 WITH LLVM-exception"
documentation = "https://docs.rs/cranelift-filetests"
repository = "https://github.com/bytecodealliance/wasmtime"
publish = false
edition = "2021"

[dependencies]
cranelift-codegen = { path = "../codegen", version = "0.89.0", features = ["testing_hooks"] }
cranelift-frontend = { path = "../frontend", version = "0.89.0" }
cranelift-interpreter = { path = "../interpreter", version = "0.89.0" }
cranelift-native = { path = "../native", version = "0.89.0" }
cranelift-reader = { path = "../reader", version = "0.89.0" }
cranelift-preopt = { path = "../preopt", version = "0.89.0" }
cranelift-jit = { path = "../jit", version = "0.89.0" }
cranelift-module = { path = "../module", version = "0.89.0" }
file-per-thread-logger = "0.1.2"
filecheck = "0.5.0"
gimli = { version = "0.26.0", default-features = false, features = ["read"] }
log = "0.4.6"
num_cpus = "1.8.0"
target-lexicon = "0.12"
thiserror = "1.0.15"
anyhow = "1.0.32"
similar = "2.1.0"
