[package]
name = "demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
getrandom = "0.2"
pku = { path = "../../pku", version = "0.1.0" }

[build-dependencies]
# cc = "1.0"