[package]
name = "component-test-util"
authors = ["The Wasmtime Project Developers"]
license = "Apache-2.0 WITH LLVM-exception"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
env_logger = "0.9.0"
anyhow = "1.0.19"
arbitrary = { version = "1.1.0", features = ["derive"] }
wasmtime = { path = "../../wasmtime", features = ["component-model"] }
