[package]
name = "wasmtime-bench-api"
version = "0.19.0"
authors = ["The Wasmtime Project Developers"]
description = "Exposes a benchmarking API for the Wasmtime runtime"
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition = "2021"
publish = false

[lib]
name = "wasmtime_bench_api"
crate-type = ["cdylib"]
test = false
doctest = false

[dependencies]
anyhow = "1.0"
shuffling-allocator = { version = "1.1.1", optional = true }
target-lexicon = "0.12"
wasmtime = { path = "../wasmtime", default-features = true }
wasmtime-cli-flags = { path = "../cli-flags", default-features = true }
wasmtime-wasi = { path = "../wasi" }
wasmtime-wasi-crypto = { path = "../wasi-crypto", optional = true }
wasmtime-wasi-nn = { path = "../wasi-nn", optional = true }
wasi-cap-std-sync = { path = "../wasi-common/cap-std-sync" }
cap-std = "0.25.3"

[dev-dependencies]
wat = "1.0.45"

[features]
default = ["shuffling-allocator"]
wasi-crypto = ["wasmtime-wasi-crypto"]
wasi-nn = ["wasmtime-wasi-nn"]
