[package]
name = "islec"
version = "0.1.0"
authors = ["The Cranelift Project Developers"]
edition = "2021"
license = "Apache-2.0 WITH LLVM-exception"
publish = false

[dependencies]
cranelift-isle = { version = "*", path = "../isle/", features = ["miette-errors", "logging"] }
env_logger = { version = "0.9", default-features = false }
miette = { version = "5.1.0", features = ["fancy"] }
clap = { version = "3.2.0", features = ["derive"] }
